spring:
  application:
    name: prueba_tecnica_1
  datasource:
    url: jdbc:mysql://localhost:3306/futbol5
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8080
